node {
   stage('Checkout') {
      checkout scm
   }
   stage('Build') {
      dir("frontend") {
         sh "rm -rf target && mkdir -p target"
         sh "zip -r target/static_content.zip index.html"
      }
   }
   stage('Publish Artifacts') {
      archive 'frontend/target/static_content.zip'
   }
}