node {
   stage('Checkout') {
      checkout scm
   }
   stage('Build Service') {
      dir("backend") {
         sh "mvn clean package"
      }
   }
   stage('Publish Artifacts') {
      archive 'backend/target/*.jar'
   }
}