---
---
- name: Install unzip
  yum: name=unzip state=present

- name: Ensure static content directory exists
  file: path=/var/www/html state=directory

- name: Get static content
  shell: ls -1 /var/www/html
  register: content

- name: Undeploy previous version of static content
  file: path=/var/www/html/{{item}} state=absent
  with_items: "{{content.stdout_lines}}"

- name: Deploy static content
  unarchive: src={{static_content_file_name}} dest=/var/www/html/
